version: "3"
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: fastorder
      POSTGRES_PASSWORD: password5786
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"